version: "3.1"

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./app:/app/app
    command: >
      bash -c '
      npm install &&
      node ./dist/index.js
      '
