version: "3.1"

services:
  backend:
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    command: /app/docker/backend/run.sh
