version: "3.1"

services:
  backend:
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ${PROJECT_ROOT}/:/app
    command: /app/docker/backend/run.sh

  nginx:
   restart: on-failure
   image: nginx:stable
   ports:
     - ${NGINX_HTTP_PORT}:3000
   env_file:
     - ${PROJECT_ROOT}/.env
   volumes:
     - ${PROJECT_ROOT}/docker/nginx/:/etc/nginx/conf.d
     - ${PROJECT_ROOT}/:/app
   depends_on:
     - backend
   links:
     - backend


#  db:
#    restart: on-failure
#    image: postgres:11
#    ports:
#      - "5432"
#    expose:
#      - "5432"
#    env_file:
#      - ./.env
#    volumes:
#      - database:/var/lib/postgresql/data
